// Auto-generated by tools/token_linter.js - DO NOT EDIT MANUALLY
module.exports = {
  theme: {
    extend: {
      colors: {
        void: '#050811',
        card: '#0B1C30',
        cyberGold: '#F9E006',
        mistCyan: '#00E5FF',
        flameCrimson: '#E11D48',
        beastEmerald: '#10B981',
        wisteriaViolet: '#C084FC',
      }
    }
  }
};
