// ============================================================
// OMNISTOCK BATCH 2: 50 GLOBAL & MID-MARKET 3PL WAREHOUSE GIANTS
// Campaign: OmniStock-Enterprise 3D WMS (omnistock.linkable.it.com)
// ============================================================

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const LEADS_FILE = path.join(__dirname, 'src', 'leads.json');
const OUTPUT_FILE = path.join(__dirname, 'OMNISTOCK_BATCH2_50_PIPELINE.json');

const OMNISTOCK_BATCH2 = [
  {
    id: "lead-os-b2-001",
    company: "Wincanton plc",
    organization: "Wincanton plc (UK Premier Supply Chain)",
    campaign: "wms",
    executiveName: "James Wroath",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/wincanton",
    email: "james.wroath@wincanton.co.uk",
    budget: "$75,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "3D Voxel digital twin picking optimization & retail distribution center floor congestion elimination",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-002",
    company: "Culina Group",
    organization: "Culina Group UK",
    campaign: "wms",
    executiveName: "Thomas van Mourik",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/culina-group-limited",
    email: "tvanmourik@culina.co.uk",
    budget: "$70,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Automated chilled food FEFO slotting quarantine & temperature zone integrity telemetry",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-003",
    company: "Clipper Logistics",
    organization: "Clipper Logistics (GXO UK)",
    campaign: "wms",
    executiveName: "Steve Parkin",
    title: "Executive Chairman & Founder",
    linkedin: "https://www.linkedin.com/company/clipper-logistics-plc",
    email: "steve.parkin@clippergroup.co.uk",
    budget: "$75,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "High-velocity fashion eCommerce return processing & dynamic high-bay rack re-allocation",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-004",
    company: "Fiege Logistics",
    organization: "Fiege Logistik Stiftung & Co. KG",
    campaign: "wms",
    executiveName: "Jens Fiege",
    title: "Co-Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/fiege-logistik",
    email: "jens.fiege@fiege.com",
    budget: "$70,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "European multi-tier fulfillment center 3D spatial twin & robotic path synchronization",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-005",
    company: "Hellmann Worldwide Logistics",
    organization: "Hellmann Worldwide Logistics",
    campaign: "wms",
    executiveName: "Jens Drewes",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/hellmann-worldwide-logistics",
    email: "jens.drewes@hellmann.com",
    budget: "$75,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Air-gapped warehouse inventory auditing & cross-dock pallet spatial telemetry",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-006",
    company: "Bleckmann Fashion Logistics",
    organization: "Bleckmann",
    campaign: "wms",
    executiveName: "Kurt Pierloot",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/bleckmann",
    email: "kurt.pierloot@bleckmann.com",
    budget: "$65,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Omni-channel lifestyle & luxury garment SKU slotting & sub-second picking wave routing",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-007",
    company: "Arvato Supply Chain Solutions",
    organization: "Arvato Supply Chain Solutions",
    campaign: "wms",
    executiveName: "Frank Schirrmeister",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/arvato-supply-chain-solutions",
    email: "frank.schirrmeister@arvato.com",
    budget: "$80,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Consumer tech & healthcare warehousing 3D digital twin & zero-dead-zone scanner integration",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-008",
    company: "Dachser European Logistics",
    organization: "Dachser SE",
    campaign: "wms",
    executiveName: "Burkhard Eling",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/dachser",
    email: "burkhard.eling@dachser.com",
    budget: "$75,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "European hub-and-spoke warehouse network 3D voxel tracking & container deconsolidation speed",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-009",
    company: "Agility Logistics",
    organization: "Agility Logistics Parks",
    campaign: "wms",
    executiveName: "Tarek Sultan",
    title: "Vice Chairman & CEO",
    linkedin: "https://www.linkedin.com/company/agility",
    email: "tsultan@agility.com",
    budget: "$85,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Mega logistics park warehouse tenant spatial intelligence & volumetric storage monetization",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-010",
    company: "Aramex Global",
    organization: "Aramex",
    campaign: "wms",
    executiveName: "Othman Aljeda",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/aramex",
    email: "othman.aljeda@aramex.com",
    budget: "$70,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Middle East express courier fulfillment depot picking route optimization & parcel sortation twin",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-011",
    company: "Kerry Logistics Asia",
    organization: "Kerry Logistics Network",
    campaign: "wms",
    executiveName: "Vic Cheung",
    title: "Managing Director",
    linkedin: "https://www.linkedin.com/company/kerry-logistics",
    email: "vic.cheung@kerrylogistics.com",
    budget: "$75,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Asia-wide automated multi-temperature facility slotting & high-density vertical carousel routing",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-012",
    company: "Sinotrans Limited",
    organization: "Sinotrans Limited",
    campaign: "wms",
    executiveName: "Song Rong",
    title: "President & Executive Director",
    linkedin: "https://www.linkedin.com/company/sinotrans",
    email: "songrong@sinotrans.com",
    budget: "$80,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Maritime port warehouse bonded storage 3D spatial allocation & customs clearance acceleration",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-013",
    company: "Yamato Transport Global",
    organization: "Yamato Transport Co., Ltd.",
    campaign: "wms",
    executiveName: "Yutaka Nagao",
    title: "President",
    linkedin: "https://www.linkedin.com/company/yamato-transport-co--ltd-",
    email: "yutaka.nagao@kuronekoyamato.co.jp",
    budget: "$85,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Zero-error automated parcel picking & ultra-high-density Japanese urban fulfillment architecture",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-014",
    company: "Verst Logistics",
    organization: "Verst Logistics",
    campaign: "wms",
    executiveName: "Paul Verst",
    title: "President & CEO",
    linkedin: "https://www.linkedin.com/company/verst-logistics",
    email: "pverst@verstlogistics.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Midwest contract packaging & multi-client 3PL warehouse picking wave optimization",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-015",
    company: "ODW Logistics",
    organization: "ODW Logistics",
    campaign: "wms",
    executiveName: "John Ness",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/odw-logistics",
    email: "jness@odwlogistics.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Integrated 3PL warehouse management & eliminating phantom stockouts on legacy WMS platforms",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-016",
    company: "Spartan Logistics",
    organization: "Spartan Logistics",
    campaign: "wms",
    executiveName: "Steve Chambers",
    title: "President",
    linkedin: "https://www.linkedin.com/company/spartan-logistics",
    email: "schambers@spartanlogistics.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Regional distribution center rail-dock staging & automated forklift pathing telemetry",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-017",
    company: "TAGG Logistics",
    organization: "TAGG Logistics",
    campaign: "wms",
    executiveName: "Tod Yazdi",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/tagg-logistics",
    email: "tyazdi@tagglogistics.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "eCommerce retail distribution fulfillment accuracy & 1-click zone re-allocation engine",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-018",
    company: "Distribution Management Inc.",
    organization: "Distribution Management Inc.",
    campaign: "wms",
    executiveName: "Sean Fleming",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/distribution-management",
    email: "sfleming@distributionmgmt.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Office technology & imaging supply warehouse pick density & automated cartonization engine",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-019",
    company: "Legacy Supply Chain",
    organization: "Legacy Supply Chain Services",
    campaign: "wms",
    executiveName: "Mike Glodziak",
    title: "President & CEO",
    linkedin: "https://www.linkedin.com/company/legacy-supply-chain-services",
    email: "mglodziak@legacyscs.com",
    budget: "$60,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "North American 3PL dedicated contract warehousing 3D volumetric slotting engine",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-020",
    company: "Buske Logistics",
    organization: "Buske Logistics",
    campaign: "wms",
    executiveName: "Todd Buske",
    title: "President",
    linkedin: "https://www.linkedin.com/company/buske-logistics",
    email: "todd.buske@buske.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Automotive supplier JIT staging & food-grade warehouse spatial lot tracking",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-021",
    company: "Evans Distribution Systems",
    organization: "Evans Distribution Systems",
    campaign: "wms",
    executiveName: "John Evans",
    title: "President",
    linkedin: "https://www.linkedin.com/company/evans-distribution-systems",
    email: "jevans@evansdist.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Automotive parts warehousing & fulfillment pick pathing with zero deadhead travel time",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-022",
    company: "Biagi Bros Logistics",
    organization: "Biagi Bros Inc.",
    campaign: "wms",
    executiveName: "Fred Biagi",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/biagi-bros",
    email: "fbiagi@biagibros.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Beverage & wine logistics 3D temperature mapping & heavy pallet stacking integrity",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-023",
    company: "Dependable Supply Chain Services",
    organization: "Dependable Supply Chain Services",
    campaign: "wms",
    executiveName: "Ron Massman",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/dependable-supply-chain-services",
    email: "rmassman@godependable.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "West Coast port-adjacent warehousing cross-docking spatial twin & container strip automation",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-024",
    company: "Jacobson Companies (XPO)",
    organization: "Jacobson Warehouse Co.",
    campaign: "wms",
    executiveName: "Scott McWilliams",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/jacobson-companies",
    email: "smcwilliams@jacobsonco.com",
    budget: "$60,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Contract warehousing & manufacturing support picking route optimization engine",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-025",
    company: "Holman Logistics",
    organization: "Holman Logistics",
    campaign: "wms",
    executiveName: "Brien Downie",
    title: "President",
    linkedin: "https://www.linkedin.com/company/holman-logistics",
    email: "bdownie@holmanusa.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Heavy paper & CPG warehouse storage optimization & clamp truck trajectory tracking",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-026",
    company: "RLS Logistics (Cold Chain)",
    organization: "RLS Logistics",
    campaign: "wms",
    executiveName: "Russell Leo",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/rls-logistics",
    email: "rleo@rlslogistics.com",
    budget: "$60,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Cold chain 3PL network sub-zero sensor integration & automated blast freezer queueing",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-027",
    company: "Hanson Logistics",
    organization: "Hanson Logistics (Lineage)",
    campaign: "wms",
    executiveName: "Ken Stevens",
    title: "President",
    linkedin: "https://www.linkedin.com/company/hanson-logistics",
    email: "kstevens@hansonlogistics.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Refrigerated food distribution & automated FEFO batch quarantine engine",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-028",
    company: "Nor-Am Cold Storage",
    organization: "Nor-Am Cold Storage",
    campaign: "wms",
    executiveName: "Shannon Coyle",
    title: "President",
    linkedin: "https://www.linkedin.com/company/nor-am-cold-storage",
    email: "scoyle@nor-am.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Meat & protein cold storage pallet racking space optimization & USDA audit logs",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-029",
    company: "Zero Mountain Cold Storage",
    organization: "Zero Mountain (Americold)",
    campaign: "wms",
    executiveName: "Joe Rumsey",
    title: "President",
    linkedin: "https://www.linkedin.com/company/zero-mountain-inc-",
    email: "jrumsey@zeromtn.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Poultry & frozen food distribution spatial digital twin with sub-second lot tracking",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-030",
    company: "Midwest Refrigerated Services",
    organization: "Midwest Refrigerated Services",
    campaign: "wms",
    executiveName: "Mike Pokel",
    title: "President",
    linkedin: "https://www.linkedin.com/company/midwest-refrigerated-services",
    email: "mpokel@midwestrefrigerated.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Multi-temperature dairy distribution center picking path efficiency & lot recall defense",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-031",
    company: "Commercial Warehousing Inc. (CWI)",
    organization: "CWI Logistics",
    campaign: "wms",
    executiveName: "Kevin Margeson",
    title: "President",
    linkedin: "https://www.linkedin.com/company/cwi-logistics",
    email: "kmargeson@cwi-logistics.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Florida Southeast distribution center ambient & cold storage volumetric optimization",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-032",
    company: "Inland Cold Storage",
    organization: "Inland Cold Storage",
    campaign: "wms",
    executiveName: "Mark Smith",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/inland-cold-storage",
    email: "msmith@inlandcold.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "High-throughput produce & agriculture cold storage rack slotting telemetry",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-033",
    company: "Preferred Freezer Services",
    organization: "Preferred Freezer Services (Lineage)",
    campaign: "wms",
    executiveName: "Patrick Gorey",
    title: "Vice President Operations",
    linkedin: "https://www.linkedin.com/company/preferred-freezer-services",
    email: "pgorey@preferredfreezer.com",
    budget: "$65,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Automated deep-freeze automated crane routing & cold-chain energy optimization",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-034",
    company: "Atlanta Bonded Warehouse",
    organization: "Atlanta Bonded Warehouse Corporation",
    campaign: "wms",
    executiveName: "Fred Perphoff",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/atlanta-bonded-warehouse",
    email: "fperphoff@atlantabonded.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Confectionery & temperature-controlled CPG warehouse cross-docking spatial twin",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-035",
    company: "Wagner Logistics",
    organization: "Wagner Logistics",
    campaign: "wms",
    executiveName: "Brian Wagner",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/wagner-logistics",
    email: "bwagner@wagnerlogistics.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Nationwide contract warehousing pick-and-pack optimization & RF scanner telemetry",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-036",
    company: "Shippers Warehouse",
    organization: "Shippers Warehouse",
    campaign: "wms",
    executiveName: "Graham Swank",
    title: "President",
    linkedin: "https://www.linkedin.com/company/shippers-warehouse",
    email: "gswank@shipperswarehouse.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Texas & Southwest food-grade CPG inventory slotting & grocery cross-docking",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-037",
    company: "DSC Logistics",
    organization: "DSC Logistics (CJ Logistics)",
    campaign: "wms",
    executiveName: "Ed Bowersox",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/dsc-logistics",
    email: "ebowersox@dsclogistics.com",
    budget: "$65,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "CPG supply chain enterprise picking waves & automated replenishment alarms",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-038",
    company: "Taylored Services",
    organization: "Taylored Services",
    campaign: "wms",
    executiveName: "Jim DeVeau",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/taylored-services",
    email: "jdeveau@tayloredservices.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Port gateway retail fulfillment & eCommerce apparel picking path optimization",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-039",
    company: "Port Jersey Logistics",
    organization: "Port Jersey Logistics",
    campaign: "wms",
    executiveName: "Rob Russo",
    title: "President",
    linkedin: "https://www.linkedin.com/company/port-jersey-logistics",
    email: "rrusso@portjersey.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "New York/New Jersey port-side specialty food & beverage temperature zone tracking",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-040",
    company: "Bonded Logistics",
    organization: "Bonded Logistics Inc.",
    campaign: "wms",
    executiveName: "Dave Clark",
    title: "President",
    linkedin: "https://www.linkedin.com/company/bonded-logistics",
    email: "dclark@bondedlogistics.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Southeast contract warehousing packaging & multi-client SKU velocity slotting",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-041",
    company: "States Logistics Services",
    organization: "States Logistics Services Inc.",
    campaign: "wms",
    executiveName: "Kirk Trombley",
    title: "President",
    linkedin: "https://www.linkedin.com/company/states-logistics-services-inc",
    email: "ktrombley@stateslogistics.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Southern California multi-client food & liquor distribution center 3D voxel routing",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-042",
    company: "Palmer Logistics",
    organization: "Palmer Logistics",
    campaign: "wms",
    executiveName: "Brett Mears",
    title: "President",
    linkedin: "https://www.linkedin.com/company/palmer-logistics",
    email: "bmears@palmerlogistics.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Houston chemical & CPG hazmat storage safety telemetry & ISO container deconsolidation",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-043",
    company: "Standard Warehouse",
    organization: "The Standard Warehouse Company",
    campaign: "wms",
    executiveName: "Bill Stenger",
    title: "President",
    linkedin: "https://www.linkedin.com/company/standard-warehouse",
    email: "bstenger@standardwarehouse.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Carolinas industrial manufacturing supply warehouse spatial staging twin",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-044",
    company: "Dunavant Enterprises",
    organization: "Dunavant Logistics Group",
    campaign: "wms",
    executiveName: "Bill Dunavant",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/dunavant-enterprises",
    email: "bdunavant@dunavant.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Cross-border logistics & drayage warehouse pallet slotting optimization",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-045",
    company: "LeSaint Logistics",
    organization: "LeSaint Logistics",
    campaign: "wms",
    executiveName: "Jeff LeSaint",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/lesaint-logistics",
    email: "jlesaint@lesaint.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Chemical & specialized manufacturing warehouse 3D inventory tracking & zero contamination",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-046",
    company: "Comprehensive Logistics",
    organization: "Comprehensive Logistics Inc.",
    campaign: "wms",
    executiveName: "Brian Kelly",
    title: "Chief Operating Officer",
    linkedin: "https://www.linkedin.com/company/comprehensive-logistics-co--inc-",
    email: "briankelly@complog.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Automotive high-precision sequencing warehouse picking path optimization",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-047",
    company: "Lanter Delivery Systems",
    organization: "Lanter Delivery Systems",
    campaign: "wms",
    executiveName: "Steve Lanter",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/lanter-delivery-systems",
    email: "slanter@lanterds.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Overnight unattended parts delivery warehouse staging & pre-sorted route queuing",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-048",
    company: "Weber Distribution",
    organization: "Weber Logistics Corp",
    campaign: "wms",
    executiveName: "Fred Weber",
    title: "Chairman",
    linkedin: "https://www.linkedin.com/company/weber-logistics",
    email: "fweber@weberlogistics.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Port logistics & temperature-controlled food-grade multi-depot spatial telemetry",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-049",
    company: "WOW Logistics Midwest",
    organization: "WOW Logistics",
    campaign: "wms",
    executiveName: "Amanda Bauer",
    title: "Vice President Operations",
    linkedin: "https://www.linkedin.com/company/wow-logistics",
    email: "abauer@wowlogistics.com",
    budget: "$50,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "High-density cheese & food ingredients warehouse 3D inventory reconciliation twin",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  },
  {
    id: "lead-os-b2-050",
    company: "Total Distribution Inc. (Peoples)",
    organization: "Total Distribution Inc. (TDI)",
    campaign: "wms",
    executiveName: "Doug Sibila",
    title: "Chief Executive Officer",
    linkedin: "https://www.linkedin.com/company/total-distribution-inc-",
    email: "dsibila@peoplesservices.com",
    budget: "$55,000 USD Perpetual / $2,500/mo Retainer",
    demoUrl: "https://omnistock.linkable.it.com",
    priorityHook: "Chemical & polymer warehouse safety spatial twin & automated inventory discrepancy alerts",
    currentTouchpoint: 1,
    status: "TOUCHPOINT_1_QUEUED"
  }
];

console.log(`📦 Assembling OmniStock Batch 2 Pipeline: ${OMNISTOCK_BATCH2.length} fresh leads.`);
fs.writeFileSync(OUTPUT_FILE, JSON.stringify(OMNISTOCK_BATCH2, null, 2), 'utf-8');
console.log(`💾 Saved to ${OUTPUT_FILE}`);

// Sync into src/leads.json
let currentLeads = [];
if (fs.existsSync(LEADS_FILE)) {
  currentLeads = JSON.parse(fs.readFileSync(LEADS_FILE, 'utf-8'));
}

const existingEmailSet = new Set(currentLeads.map(l => (l.email || '').toLowerCase().trim()));
let added = 0;
for (const lead of OMNISTOCK_BATCH2) {
  const norm = (lead.email || '').toLowerCase().trim();
  if (!existingEmailSet.has(norm)) {
    currentLeads.push(lead);
    existingEmailSet.add(norm);
    added++;
  }
}

fs.writeFileSync(LEADS_FILE, JSON.stringify(currentLeads, null, 2), 'utf-8');
console.log(`✅ Synced into ${LEADS_FILE}: Added ${added} fresh leads. Total leads in system: ${currentLeads.length}`);
