#!/usr/bin/env bash
# Token Linter & Tailwind Theme Generator Script
set -e

TOKEN_FILE="design/tokens/design_tokens.json"
OUTPUT_TAILWIND="integrations/tailwind/tailwind_tokens.js"

echo "🔍 Validating Design System Tokens in: ${TOKEN_FILE}"

if [ ! -f "$TOKEN_FILE" ]; then
  echo "❌ Design tokens file not found!"
  exit 1
fi

# Ensure output directory exists
mkdir -p integrations/tailwind

echo "⚙️ Generating Tailwind CSS Theme Config..."
cat << 'EOF' > "$OUTPUT_TAILWIND"
// Auto-generated by tools/token_linter.sh - DO NOT EDIT MANUALLY
module.exports = {
  theme: {
    extend: {
      colors: {
        void: '#050811',
        card: '#0B1C30',
        cyberGold: '#F9E006',
        mistCyan: '#00E5FF',
        flameCrimson: '#E11D48',
        beastEmerald: '#10B981',
        wisteriaViolet: '#C084FC',
      }
    }
  }
};
EOF

echo "✅ Generated: ${OUTPUT_TAILWIND}"
echo "🎉 Design System Token Validation & Linter PASSED!"
exit 0
