/**
 * Cross-Platform Token Linter & Tailwind Config Generator
 */
const fs = require('fs');
const path = require('path');

const TOKEN_FILE = path.join(__dirname, '..', 'design', 'tokens', 'design_tokens.json');
const OUTPUT_DIR = path.join(__dirname, '..', 'integrations', 'tailwind');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'tailwind_tokens.js');

console.log(`🔍 Validating Design System Tokens: ${TOKEN_FILE}`);

if (!fs.existsSync(TOKEN_FILE)) {
  console.error(`❌ Error: Design tokens file missing at ${TOKEN_FILE}`);
  process.exit(1);
}

try {
  const raw = fs.readFileSync(TOKEN_FILE, 'utf8');
  const tokens = JSON.parse(raw);
  
  if (!tokens.colors || !tokens.typography || !tokens.semantic) {
    console.error(`❌ Error: Tokens missing required schema sections (colors, typography, semantic).`);
    process.exit(1);
  }

  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  const tailwindConfig = `// Auto-generated by tools/token_linter.js - DO NOT EDIT MANUALLY
module.exports = {
  theme: {
    extend: {
      colors: {
        void: '${tokens.semantic.surface}',
        card: '${tokens.semantic.card}',
        cyberGold: '${tokens.colors.accent.gold}',
        mistCyan: '${tokens.colors.accent.cyan}',
        flameCrimson: '${tokens.colors.accent.crimson}',
        beastEmerald: '${tokens.colors.accent.emerald}',
        wisteriaViolet: '${tokens.colors.accent.violet}',
      }
    }
  }
};
`;

  fs.writeFileSync(OUTPUT_FILE, tailwindConfig, 'utf8');
  console.log(`✅ Generated Tailwind Config Tokens: ${OUTPUT_FILE}`);
  console.log(`🎉 Design System Token Validation & Linter PASSED!\n`);
  process.exit(0);
} catch (err) {
  console.error(`❌ Token Linter Error: ${err.message}`);
  process.exit(1);
}
